INF-993 - Adicionar a chamada para a nova rota no GAPI para fazer o get do token para autenticar na plugpag
wirecardBrasil/moip-sdk-java-le pull request #141
Opened 2021-03-19 12:40 UTC by brunovellego

task: https://moippagamentos.atlassian.net/browse/INF-993

2021-03-19 12:44 UTC, dpunta requested changes
faltam os testes para a nova API

2021-03-19 12:44 UTC, dpunta commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-3.0-bin.zip
não sei se podemos mudar isso

2021-03-19 12:44 UTC, dpunta commented on src/main/java/br/com/moip/API.java
> +import br.com.moip.api.*;
não seria melhor só acrescentar a PlugPagTokenAPI?

2021-03-19 12:47 UTC, brunovellego commented on src/main/java/br/com/moip/API.java
> +import br.com.moip.api.*;
esse import foi automático

2021-03-19 12:47 UTC, brunovellego commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-3.0-bin.zip
voltei pra o antigo

2021-03-19 12:47 UTC, guilherme-wirecard commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-3.0-bin.zip
Acredito que possa ser alterada a versão do wrapper.

2021-03-19 12:51 UTC, brunovellego commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-3.0-bin.zip
eita... eu deixo no 2.3 ou no 3?

2021-03-19 19:08 UTC, brunovellego commented
> faltam os testes para a nova API



> faltam os testes para a nova API

feito

2021-03-19 19:27 UTC, guilherme-wirecard approved these changes

2021-03-23 12:32 UTC, dpunta commented on src/main/java/br/com/moip/API.java
> +import br.com.moip.api.*;
Pode colocar de novo separados acrescentando só o novo :)

2021-03-23 12:43 UTC, brunovellego commented on src/main/java/br/com/moip/API.java
> +import br.com.moip.api.*;
feito

2021-03-23 12:45 UTC, dpunta approved these changes

2021-03-23 12:48 UTC, merged